package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action", schema = "public")
public class Action implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "classPath", column = @Column(name = "class_path", nullable = false, length = 200)),
			@AttributeOverride(name = "actionInvoker", column = @Column(name = "action_invoker", nullable = false, length = 200)) })
	private ActionId id;

	@Column(name = "idaction", nullable = false)
	private int idaction;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "group_has_action", schema = "public", joinColumns = {
					@JoinColumn(name = "action_class_path", nullable = false, updatable = false),
					@JoinColumn(name = "action_action_invoker", nullable = false, updatable = false) }, 
			inverseJoinColumns = { 
					@JoinColumn(name = "group_idgroup", nullable = false, updatable = false) }
			)
	private Set<Group> groups = new HashSet<Group>(0);

	public Action() {
	}

	public Action(ActionId id, int idaction) {
		this.id = id;
		this.idaction = idaction;
	}

	public Action(ActionId id, int idaction, Set<Group> groups) {
		this.id = id;
		this.idaction = idaction;
		this.groups = groups;
	}

	public ActionId getId() {
		return this.id;
	}

	public void setId(ActionId id) {
		this.id = id;
	}

	public int getIdaction() {
		return this.idaction;
	}

	public void setIdaction(int idaction) {
		this.idaction = idaction;
	}

	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

}
