package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Adress generated by hbm2java
 */
@Entity
@Table(name = "adress", schema = "public")
public class Adress implements java.io.Serializable {

	@Id
	@SequenceGenerator(name = "adress_sequence", sequenceName = "adress_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="adress_sequence") 
	@Column(name = "idadress", unique = true, nullable = false)
	private int idadress;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_idcity", nullable = false, insertable = false, updatable = false)
	private City city;
	
	@Column(name = "city_idcity", nullable = false, insertable = true, updatable = true)
	private Integer idCity;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_idprofile", nullable = false, insertable = false, updatable = false)
	private Profile profile;
	
	@Column(name = "profile_idprofile", nullable = false, insertable = true, updatable = true)
	private Integer idProfile;

	@Column(name = "street", length = 200)
	private String street;

	@Column(name = "number")
	private Integer number;

	@Column(name = "otherinfo", length = 600)
	private String otherinfo;

	@Column(name = "lat", length = 45)
	private String lat;

	@Column(name = "lon", length = 45)
	private String lon;

	public Adress() {
	}

	public Adress(int idadress, City city, Profile profile) {
		this.idadress = idadress;
		this.city = city;
		this.idCity = city.getIdcity();
		this.profile = profile;
		this.idProfile = profile.getIdprofile();
	}

	public Adress(int idadress, City city, Profile profile, String street,
			Integer number, String otherinfo, String lat, String lon) {
		this.idadress = idadress;
		this.city = city;
		this.idCity = city.getIdcity();
		this.profile = profile;
		this.idProfile = profile.getIdprofile();
		this.street = street;
		this.number = number;
		this.otherinfo = otherinfo;
		this.lat = lat;
		this.lon = lon;
	}

	public int getIdadress() {
		return this.idadress;
	}

	public void setIdadress(int idadress) {
		this.idadress = idadress;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getOtherinfo() {
		return this.otherinfo;
	}

	public void setOtherinfo(String otherinfo) {
		this.otherinfo = otherinfo;
	}

	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getLon() {
		return this.lon;
	}

	public void setLon(String lon) {
		this.lon = lon;
	}

	public Integer getIdCity() {
		return idCity;
	}

	public void setIdCity(Integer idCity) {
		this.idCity = idCity;
	}

	public Integer getIdProfile() {
		return idProfile;
	}

	public void setIdProfile(Integer idProfile) {
		this.idProfile = idProfile;
	}
	
	

}
