package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Avatar generated by hbm2java
 */
@Entity
@Table(name = "avatar", schema = "public")
public class Avatar implements java.io.Serializable {

	@Id
	@Column(name = "idavatar", unique = true, nullable = false)
	@SequenceGenerator(name = "avatar_seq", sequenceName = "avatar_idavatar_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="avatar_seq") 
	private int idavatar;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_idprofile", nullable = false, insertable = false, updatable = false)
	private Profile profile;
	
	@Column(name = "profile_idprofile", nullable = false, insertable = true, updatable = true)
	private Integer idProfile;

	@Column(name = "path", nullable = false, length = 200)
	private String path;

	public Avatar() {
	}

	public Avatar(int idavatar, Profile profile, String path) {
		this.idavatar = idavatar;
		this.profile = profile;
		this.path = path;
		this.idProfile = profile.getIdprofile();
	}

	public int getIdavatar() {
		return this.idavatar;
	}

	public void setIdavatar(int idavatar) {
		this.idavatar = idavatar;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Integer getIdProfile() {
		return idProfile;
	}

	public void setIdProfile(Integer idProfile) {
		this.idProfile = idProfile;
	}

}
