package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", schema = "public")
public class City implements java.io.Serializable {

	@Id
	@Column(name = "idcity", unique = true, nullable = false)
	@SequenceGenerator(name = "city_seq", sequenceName = "city_idcity_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="city_seq") 
	private int idcity;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_idstate", nullable = false, insertable = false, updatable = false)
	private State state;
	
	@Column(name = "state_idstate", nullable = false, insertable = true, updatable = true)
	private Integer idState;

	@Column(name = "nm_city", length = 200)
	private String nmCity;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	private Set<Adress> adresses = new HashSet<Adress>(0);

	public City() {
	}

	public City(int idcity, State state) {
		this.idcity = idcity;
		this.state = state;
		this.idState = state.getIdstate();
	}

	public City(int idcity, State state, String nmCity, Set<Adress> adresses) {
		this.idcity = idcity;
		this.state = state;
		this.nmCity = nmCity;
		this.adresses = adresses;
		this.idState = state.getIdstate();
	}

	public int getIdcity() {
		return this.idcity;
	}

	public void setIdcity(int idcity) {
		this.idcity = idcity;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getNmCity() {
		return this.nmCity;
	}

	public void setNmCity(String nmCity) {
		this.nmCity = nmCity;
	}

	public Set<Adress> getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Set<Adress> adresses) {
		this.adresses = adresses;
	}

	public Integer getIdState() {
		return idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}
	

}
