package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DataSourceType generated by hbm2java
 */
@Entity
@Table(name = "data_source_type", schema = "public")
public class DataSourceType implements java.io.Serializable {
	
	@Id
	@SequenceGenerator(name = "data_source_type_seq", sequenceName = "data_source_type_iddata_source_type_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="data_source_type_seq") 
	@Column(name = "iddata_source_type", unique = true, nullable = false)
	private int iddataSourceType;

	@Column(name = "de_source_type", length = 100)
	private String deSourceType;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataSourceType")
	private Set<DataSource> dataSources = new HashSet<DataSource>(0);

	public DataSourceType() {
	}

	public DataSourceType(int iddataSourceType) {
		this.iddataSourceType = iddataSourceType;
	}

	public DataSourceType(int iddataSourceType, String deSourceType,
			Set<DataSource> dataSources) {
		this.iddataSourceType = iddataSourceType;
		this.deSourceType = deSourceType;
		this.dataSources = dataSources;
	}

	public int getIddataSourceType() {
		return this.iddataSourceType;
	}

	public void setIddataSourceType(int iddataSourceType) {
		this.iddataSourceType = iddataSourceType;
	}

	public String getDeSourceType() {
		return this.deSourceType;
	}

	public void setDeSourceType(String deSourceType) {
		this.deSourceType = deSourceType;
	}

	public Set<DataSource> getDataSources() {
		return this.dataSources;
	}

	public void setDataSources(Set<DataSource> dataSources) {
		this.dataSources = dataSources;
	}

}
