package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DataSourceDriver generated by hbm2java
 */
@Entity
@Table(name = "data_source_driver", schema = "public")
public class DataSourceDriver implements java.io.Serializable {

	@Id
	@SequenceGenerator(name = "data_source_driver_seq", sequenceName = "data_source_driver_iddata_source_driver_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="data_source_driver_seq") 
	@Column(name = "iddata_source_driver", unique = true, nullable = false)
	private int iddataSourceDriver;

	@Column(name = "class_path", nullable = false, length = 200)
	private String classPath;

	@Column(name = "data_source_drivercol", length = 45)
	private String dataSourceDrivercol;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataSourceDriver")
	private Set<ShareView> shareViews = new HashSet<ShareView>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataSourceDriver")
	private Set<DataSource> dataSources = new HashSet<DataSource>(0);

	public DataSourceDriver() {
	}

	public DataSourceDriver(int iddataSourceDriver, String classPath) {
		this.iddataSourceDriver = iddataSourceDriver;
		this.classPath = classPath;
	}

	public DataSourceDriver(int iddataSourceDriver, String classPath,
			String dataSourceDrivercol, Set<ShareView> shareViews,
			Set<DataSource> dataSources) {
		this.iddataSourceDriver = iddataSourceDriver;
		this.classPath = classPath;
		this.dataSourceDrivercol = dataSourceDrivercol;
		this.shareViews = shareViews;
		this.dataSources = dataSources;
	}

	public int getIddataSourceDriver() {
		return this.iddataSourceDriver;
	}

	public void setIddataSourceDriver(int iddataSourceDriver) {
		this.iddataSourceDriver = iddataSourceDriver;
	}

	public String getClassPath() {
		return this.classPath;
	}

	public void setClassPath(String classPath) {
		this.classPath = classPath;
	}

	public String getDataSourceDrivercol() {
		return this.dataSourceDrivercol;
	}

	public void setDataSourceDrivercol(String dataSourceDrivercol) {
		this.dataSourceDrivercol = dataSourceDrivercol;
	}

	public Set<ShareView> getShareViews() {
		return this.shareViews;
	}

	public void setShareViews(Set<ShareView> shareViews) {
		this.shareViews = shareViews;
	}

	public Set<DataSource> getDataSources() {
		return this.dataSources;
	}

	public void setDataSources(Set<DataSource> dataSources) {
		this.dataSources = dataSources;
	}

}
