package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DataSourceDriverOutput generated by hbm2java
 */
@Entity
@Table(name = "data_source_driver_output", schema = "public")
public class DataSourceDriverOutput implements java.io.Serializable {

	@Id
	@Column(name = "iddata_source_driver", unique = true, nullable = false)
	private int iddataSourceDriver;

	@Column(name = "class_path", nullable = false, length = 200)
	private String classPath;

	@Column(name = "data_source_drivercol", length = 45)
	private String dataSourceDrivercol;

	public DataSourceDriverOutput() {
	}

	public DataSourceDriverOutput(int iddataSourceDriver, String classPath) {
		this.iddataSourceDriver = iddataSourceDriver;
		this.classPath = classPath;
	}

	public DataSourceDriverOutput(int iddataSourceDriver, String classPath,
			String dataSourceDrivercol) {
		this.iddataSourceDriver = iddataSourceDriver;
		this.classPath = classPath;
		this.dataSourceDrivercol = dataSourceDrivercol;
	}

	public int getIddataSourceDriver() {
		return this.iddataSourceDriver;
	}

	public void setIddataSourceDriver(int iddataSourceDriver) {
		this.iddataSourceDriver = iddataSourceDriver;
	}

	public String getClassPath() {
		return this.classPath;
	}

	public void setClassPath(String classPath) {
		this.classPath = classPath;
	}

	public String getDataSourceDrivercol() {
		return this.dataSourceDrivercol;
	}

	public void setDataSourceDrivercol(String dataSourceDrivercol) {
		this.dataSourceDrivercol = dataSourceDrivercol;
	}

}
