package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * DataSource generated by hbm2java
 */
@Entity
@Table(name = "data_source", schema = "public")
public class DataSource implements java.io.Serializable {

	@Id
	@SequenceGenerator(name = "data_source_seq", sequenceName = "data_source_iddata_source_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="data_source_seq") 
	@Column(name = "iddata_source", unique = true, nullable = false)
	private int iddataSource;

	@Version
	@Column(name = "version")
	private Integer version;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "data_source_driver_iddata_source_driver", nullable = false, insertable = false, updatable = false)
	private DataSourceDriver dataSourceDriver;
	
	@Column(name = "data_source_driver_iddata_source_driver", nullable = false, insertable = true, updatable = true)
	private Integer idDataSourceDriver;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "data_source_type_iddata_source_type", nullable = false, insertable = false, updatable = false)
	private DataSourceType dataSourceType;
	
	@Column(name = "data_source_type_iddata_source_type", nullable = false, insertable = true, updatable = true)
	private Integer idDataSourceType;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddata_source_relatedto", insertable = false, updatable = false)
	private DataSource dataSourceRelatedTo;
	
	@Column(name = "iddata_source_relatedto", insertable = true, updatable = true)
	private Integer idDataSourceRelatedTo;

	@Column(name = "de_datasource", length = 600)
	private String deDatasource;

	@Column(name = "nm_datasource", length = 200)
	private String nmDatasource;

	@Column(name = "data_source_url", length = 250)
	private String dataSourceUrl;

	@Column(name = "data_password", length = 45)
	private String dataPassword;

	@Column(name = "enabled")
	private Boolean enabled;

	@Column(name = "data_username", length = 45)
	private String dataUsername;

	@Column(name = "lat", length = 45)
	private String lat;

	@Column(name = "lon", length = 45)
	private String lon;

	@Column(name = "schema", length = 200)
	private String schema;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataSource")
	private Set<Info> infos = new HashSet<Info>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataSource")
	private Set<ShareView> shareViews = new HashSet<ShareView>(0);

	public DataSource() {
	}

	public DataSource(int iddataSource, DataSourceDriver dataSourceDriver,
			DataSourceType dataSourceType) {
		this.iddataSource = iddataSource;
		this.dataSourceDriver = dataSourceDriver;
		this.idDataSourceDriver = dataSourceDriver.getIddataSourceDriver();
		this.dataSourceType = dataSourceType;
		this.idDataSourceType = dataSourceType.getIddataSourceType();
	}

	public DataSource(int iddataSource, DataSourceDriver dataSourceDriver,
			DataSourceType dataSourceType, DataSource dataSourceRelatedTo,
			String deDatasource, String nmDatasource, String dataSourceUrl,
			String dataPassword, Boolean enabled, String dataUsername,
			String lat, String lon, String schema,
			Set<Info> infos, Set<ShareView> shareViews,
			Set<DataSource> dataSources) {
		this.iddataSource = iddataSource;
		this.dataSourceDriver = dataSourceDriver;
		this.idDataSourceDriver = dataSourceDriver.getIddataSourceDriver();
		this.dataSourceType = dataSourceType;
		this.idDataSourceType = dataSourceType.getIddataSourceType();
		this.dataSourceRelatedTo = dataSourceRelatedTo;
		if(dataSourceRelatedTo!=null){
			this.idDataSourceRelatedTo = dataSourceRelatedTo.getIddataSource();
		}
		this.deDatasource = deDatasource;
		this.nmDatasource = nmDatasource;
		this.dataSourceUrl = dataSourceUrl;
		this.dataPassword = dataPassword;
		this.enabled = enabled;
		this.dataUsername = dataUsername;
		this.lat = lat;
		this.lon = lon;
		this.schema = schema;
		this.infos = infos;
		this.shareViews = shareViews;
	}

	public int getIddataSource() {
		return this.iddataSource;
	}

	public void setIddataSource(int iddataSource) {
		this.iddataSource = iddataSource;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public DataSourceDriver getDataSourceDriver() {
		return this.dataSourceDriver;
	}

	public void setDataSourceDriver(DataSourceDriver dataSourceDriver) {
		this.dataSourceDriver = dataSourceDriver;
	}

	public DataSourceType getDataSourceType() {
		return this.dataSourceType;
	}

	public void setDataSourceType(DataSourceType dataSourceType) {
		this.dataSourceType = dataSourceType;
	}

	public DataSource getDataSource() {
		return this.dataSourceRelatedTo;
	}

	public void setDataSource(DataSource dataSource) {
		this.dataSourceRelatedTo = dataSource;
	}

	public String getDeDatasource() {
		return this.deDatasource;
	}

	public void setDeDatasource(String deDatasource) {
		this.deDatasource = deDatasource;
	}

	public String getNmDatasource() {
		return this.nmDatasource;
	}

	public void setNmDatasource(String nmDatasource) {
		this.nmDatasource = nmDatasource;
	}

	public String getDataSourceUrl() {
		return this.dataSourceUrl;
	}

	public void setDataSourceUrl(String dataSourceUrl) {
		this.dataSourceUrl = dataSourceUrl;
	}

	public String getDataPassword() {
		return this.dataPassword;
	}

	public void setDataPassword(String dataPassword) {
		this.dataPassword = dataPassword;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getDataUsername() {
		return this.dataUsername;
	}

	public void setDataUsername(String dataUsername) {
		this.dataUsername = dataUsername;
	}

	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getLon() {
		return this.lon;
	}

	public void setLon(String lon) {
		this.lon = lon;
	}

	public String getSchema() {
		return this.schema;
	}

	public void setSchema(String schema) {
		this.schema = schema;
	}

	public Set<Info> getInfos() {
		return this.infos;
	}

	public void setInfos(Set<Info> infos) {
		this.infos = infos;
	}

	public Set<ShareView> getShareViews() {
		return this.shareViews;
	}

	public void setShareViews(Set<ShareView> shareViews) {
		this.shareViews = shareViews;
	}

	public Integer getIdDataSourceDriver() {
		return idDataSourceDriver;
	}

	public void setIdDataSourceDriver(Integer idDataSourceDriver) {
		this.idDataSourceDriver = idDataSourceDriver;
	}

	public Integer getIdDataSourceType() {
		return idDataSourceType;
	}

	public void setIdDataSourceType(Integer idDataSourceType) {
		this.idDataSourceType = idDataSourceType;
	}

	public DataSource getDataSourceRelatedTo() {
		return dataSourceRelatedTo;
	}

	public void setDataSourceRelatedTo(DataSource dataSourceRelatedTo) {
		this.dataSourceRelatedTo = dataSourceRelatedTo;
	}

	public Integer getIdDataSourceRelatedTo() {
		return idDataSourceRelatedTo;
	}

	public void setIdDataSourceRelatedTo(Integer idDataSourceRelatedTo) {
		this.idDataSourceRelatedTo = idDataSourceRelatedTo;
	}
	
	
}
