package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FieldMask generated by hbm2java
 */
@Entity
@Table(name = "field_mask", schema = "public")
public class FieldMask implements java.io.Serializable {

	@Id
	@Column(name = "idfield_mask", unique = true, nullable = false)
	private int idfieldMask;

	@Column(name = "nm_mask", nullable = false, length = 50)
	private String nmMask;

	@Column(name = "de_mask", length = 300)
	private String deMask;

	@Column(name = "my_mask", nullable = false, length = 300)
	private String myMask;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldMask")
	private Set<Field> fields = new HashSet<Field>(0);

	public FieldMask() {
	}

	public FieldMask(int idfieldMask, String nmMask, String myMask) {
		this.idfieldMask = idfieldMask;
		this.nmMask = nmMask;
		this.myMask = myMask;
	}

	public FieldMask(int idfieldMask, String nmMask, String deMask,
			String myMask, Set<Field> fields) {
		this.idfieldMask = idfieldMask;
		this.nmMask = nmMask;
		this.deMask = deMask;
		this.myMask = myMask;
		this.fields = fields;
	}

	public int getIdfieldMask() {
		return this.idfieldMask;
	}

	public void setIdfieldMask(int idfieldMask) {
		this.idfieldMask = idfieldMask;
	}

	public String getNmMask() {
		return this.nmMask;
	}

	public void setNmMask(String nmMask) {
		this.nmMask = nmMask;
	}

	public String getDeMask() {
		return this.deMask;
	}

	public void setDeMask(String deMask) {
		this.deMask = deMask;
	}

	public String getMyMask() {
		return this.myMask;
	}

	public void setMyMask(String myMask) {
		this.myMask = myMask;
	}

	public Set<Field> getFields() {
		return this.fields;
	}

	public void setFields(Set<Field> fields) {
		this.fields = fields;
	}

}
