package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FieldType generated by hbm2java
 */
@Entity
@Table(name = "field_type", schema = "public")
public class FieldType implements java.io.Serializable {

	@Id
	@Column(name = "idfield_type", unique = true, nullable = false)
	private int idfieldType;

	@Column(name = "nm_type", length = 30)
	private String nmType;

	@Column(name = "field_typecol", length = 45)
	private String fieldTypecol;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldType")
	private Set<Field> fields = new HashSet<Field>(0);

	public FieldType() {
	}

	public FieldType(int idfieldType) {
		this.idfieldType = idfieldType;
	}

	public FieldType(int idfieldType, String nmType, String fieldTypecol,
			Set<Field> fields) {
		this.idfieldType = idfieldType;
		this.nmType = nmType;
		this.fieldTypecol = fieldTypecol;
		this.fields = fields;
	}

	public int getIdfieldType() {
		return this.idfieldType;
	}

	public void setIdfieldType(int idfieldType) {
		this.idfieldType = idfieldType;
	}

	public String getNmType() {
		return this.nmType;
	}

	public void setNmType(String nmType) {
		this.nmType = nmType;
	}

	public String getFieldTypecol() {
		return this.fieldTypecol;
	}

	public void setFieldTypecol(String fieldTypecol) {
		this.fieldTypecol = fieldTypecol;
	}

	public Set<Field> getFields() {
		return this.fields;
	}

	public void setFields(Set<Field> fields) {
		this.fields = fields;
	}

}
