package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "group", schema = "public")
public class Group implements java.io.Serializable {

	@Id
	@Column(name = "idgroup", unique = true, nullable = false)
	private int idgroup;

	@Column(name = "name", nullable = false, length = 45)
	private String name;

	@Column(name = "description", length = 400)
	private String description;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "group_has_action", schema = "public", joinColumns = { 
					@JoinColumn(name = "group_idgroup", nullable = false, updatable = false) }, 
					inverseJoinColumns = { 
					@JoinColumn(name = "action_class_path", nullable = false, updatable = false),
					@JoinColumn(name = "action_action_invoker", nullable = false, updatable = false)})
	private Set<Action> actions = new HashSet<Action>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "group")
	private Set<GroupHasProfile> groupHasProfiles = new HashSet<GroupHasProfile>(
			0);

	public Group() {
	}

	public Group(int idgroup, String name) {
		this.idgroup = idgroup;
		this.name = name;
	}

	public Group(int idgroup, String name, String description,
			Set<Action> actions, Set<GroupHasProfile> groupHasProfiles) {
		this.idgroup = idgroup;
		this.name = name;
		this.description = description;
		this.actions = actions;
		this.groupHasProfiles = groupHasProfiles;
	}

	public int getIdgroup() {
		return this.idgroup;
	}

	public void setIdgroup(int idgroup) {
		this.idgroup = idgroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Action> getActions() {
		return this.actions;
	}

	public void setActions(Set<Action> actions) {
		this.actions = actions;
	}

	public Set<GroupHasProfile> getGroupHasProfiles() {
		return this.groupHasProfiles;
	}

	public void setGroupHasProfiles(Set<GroupHasProfile> groupHasProfiles) {
		this.groupHasProfiles = groupHasProfiles;
	}

}
