package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupHasProfileId generated by hbm2java
 */
@Embeddable
public class GroupHasProfileId implements java.io.Serializable {

	@Column(name = "group_idgroup", nullable = false)
	private int groupIdgroup;

	@Column(name = "profile_idprofile", nullable = false)
	private int profileIdprofile;

	public GroupHasProfileId() {
	}

	public GroupHasProfileId(int groupIdgroup, int profileIdprofile) {
		this.groupIdgroup = groupIdgroup;
		this.profileIdprofile = profileIdprofile;
	}

	public int getGroupIdgroup() {
		return this.groupIdgroup;
	}

	public void setGroupIdgroup(int groupIdgroup) {
		this.groupIdgroup = groupIdgroup;
	}

	public int getProfileIdprofile() {
		return this.profileIdprofile;
	}

	public void setProfileIdprofile(int profileIdprofile) {
		this.profileIdprofile = profileIdprofile;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupHasProfileId))
			return false;
		GroupHasProfileId castOther = (GroupHasProfileId) other;

		return (this.getGroupIdgroup() == castOther.getGroupIdgroup())
				&& (this.getProfileIdprofile() == castOther
						.getProfileIdprofile());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupIdgroup();
		result = 37 * result + this.getProfileIdprofile();
		return result;
	}

}
