package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProfileContact generated by hbm2java
 */
@Entity
@Table(name = "profile_contact", schema = "public")
public class ProfileContact implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "profileIdprofile", column = @Column(name = "profile_idprofile", nullable = false)),
			@AttributeOverride(name = "profileIdprofile1", column = @Column(name = "profile_idprofile1", nullable = false)) })
	private ProfileContactId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_idprofile1", nullable = false, insertable = false, updatable = false)
	private Profile profileByProfileIdprofile1;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_idprofile", nullable = false, insertable = false, updatable = false)
	private Profile profileByProfileIdprofile;

	@Column(name = "enabled")
	private Boolean enabled;

	public ProfileContact() {
	}

	public ProfileContact(ProfileContactId id,
			Profile profileByProfileIdprofile1,
			Profile profileByProfileIdprofile) {
		this.id = id;
		this.profileByProfileIdprofile1 = profileByProfileIdprofile1;
		this.profileByProfileIdprofile = profileByProfileIdprofile;
	}

	public ProfileContact(ProfileContactId id,
			Profile profileByProfileIdprofile1,
			Profile profileByProfileIdprofile, Boolean enabled) {
		this.id = id;
		this.profileByProfileIdprofile1 = profileByProfileIdprofile1;
		this.profileByProfileIdprofile = profileByProfileIdprofile;
		this.enabled = enabled;
	}

	public ProfileContactId getId() {
		return this.id;
	}

	public void setId(ProfileContactId id) {
		this.id = id;
	}

	public Profile getProfileByProfileIdprofile1() {
		return this.profileByProfileIdprofile1;
	}

	public void setProfileByProfileIdprofile1(Profile profileByProfileIdprofile1) {
		this.profileByProfileIdprofile1 = profileByProfileIdprofile1;
	}

	public Profile getProfileByProfileIdprofile() {
		return this.profileByProfileIdprofile;
	}

	public void setProfileByProfileIdprofile(Profile profileByProfileIdprofile) {
		this.profileByProfileIdprofile = profileByProfileIdprofile;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

}
