package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelationshipId generated by hbm2java
 */
@Embeddable
public class RelationshipId implements java.io.Serializable {

	@Column(name = "field_iddata_from", nullable = false)
	private int fieldIddataFrom;

	@Column(name = "field_iddata_to", nullable = false)
	private int fieldIddataTo;

	public RelationshipId() {
	}

	public RelationshipId(int fieldIddataFrom, int fieldIddataTo) {
		this.fieldIddataFrom = fieldIddataFrom;
		this.fieldIddataTo = fieldIddataTo;
	}

	public int getFieldIddataFrom() {
		return this.fieldIddataFrom;
	}

	public void setFieldIddataFrom(int fieldIddataFrom) {
		this.fieldIddataFrom = fieldIddataFrom;
	}

	public int getFieldIddataTo() {
		return this.fieldIddataTo;
	}

	public void setFieldIddataTo(int fieldIddataTo) {
		this.fieldIddataTo = fieldIddataTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelationshipId))
			return false;
		RelationshipId castOther = (RelationshipId) other;

		return (this.getFieldIddataFrom() == castOther.getFieldIddataFrom())
				&& (this.getFieldIddataTo() == castOther.getFieldIddataTo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFieldIddataFrom();
		result = 37 * result + this.getFieldIddataTo();
		return result;
	}

}
