package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Relationship generated by hbm2java
 */
@Entity
@Table(name = "relationship", schema = "public")
public class Relationship implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fieldIddataFrom", column = @Column(name = "field_iddata_from", nullable = false)),
			@AttributeOverride(name = "fieldIddataTo", column = @Column(name = "field_iddata_to", nullable = false)) })
	private RelationshipId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "field_iddata_from", nullable = false, insertable = false, updatable = false)
	private Field fieldByFieldIddataFrom;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "field_iddata_to", nullable = false, insertable = false, updatable = false)
	private Field fieldByFieldIddataTo;

	@Column(name = "required", nullable = false)
	private boolean required;

	@Column(name = "description", length = 150)
	private String description;

	public Relationship() {
	}

	public Relationship(RelationshipId id, Field fieldByFieldIddataFrom,
			Field fieldByFieldIddataTo, boolean required) {
		this.id = id;
		this.fieldByFieldIddataFrom = fieldByFieldIddataFrom;
		this.fieldByFieldIddataTo = fieldByFieldIddataTo;
		this.required = required;
	}

	public Relationship(RelationshipId id, Field fieldByFieldIddataFrom,
			Field fieldByFieldIddataTo, boolean required, String description) {
		this.id = id;
		this.fieldByFieldIddataFrom = fieldByFieldIddataFrom;
		this.fieldByFieldIddataTo = fieldByFieldIddataTo;
		this.required = required;
		this.description = description;
	}

	public RelationshipId getId() {
		return this.id;
	}

	public void setId(RelationshipId id) {
		this.id = id;
	}

	public Field getFieldByFieldIddataFrom() {
		return this.fieldByFieldIddataFrom;
	}

	public void setFieldByFieldIddataFrom(Field fieldByFieldIddataFrom) {
		this.fieldByFieldIddataFrom = fieldByFieldIddataFrom;
	}

	public Field getFieldByFieldIddataTo() {
		return this.fieldByFieldIddataTo;
	}

	public void setFieldByFieldIddataTo(Field fieldByFieldIddataTo) {
		this.fieldByFieldIddataTo = fieldByFieldIddataTo;
	}

	public boolean isRequired() {
		return this.required;
	}

	public void setRequired(boolean required) {
		this.required = required;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
