package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShareViewWithId generated by hbm2java
 */
@Embeddable
public class ShareViewWithId implements java.io.Serializable {

	@Column(name = "idprofile_user", nullable = false)
	private int idprofileUser;

	@Column(name = "iddata_source", nullable = false)
	private int iddataSource;

	@Column(name = "idprofile_owner", nullable = false)
	private int idprofileOwner;

	public ShareViewWithId() {
	}

	public ShareViewWithId(int idprofileUser, int iddataSource,
			int idprofileOwner) {
		this.idprofileUser = idprofileUser;
		this.iddataSource = iddataSource;
		this.idprofileOwner = idprofileOwner;
	}

	public int getIdprofileUser() {
		return this.idprofileUser;
	}

	public void setIdprofileUser(int idprofileUser) {
		this.idprofileUser = idprofileUser;
	}

	public int getIddataSource() {
		return this.iddataSource;
	}

	public void setIddataSource(int iddataSource) {
		this.iddataSource = iddataSource;
	}

	public int getIdprofileOwner() {
		return this.idprofileOwner;
	}

	public void setIdprofileOwner(int idprofileOwner) {
		this.idprofileOwner = idprofileOwner;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShareViewWithId))
			return false;
		ShareViewWithId castOther = (ShareViewWithId) other;

		return (this.getIdprofileUser() == castOther.getIdprofileUser())
				&& (this.getIddataSource() == castOther.getIddataSource())
				&& (this.getIdprofileOwner() == castOther.getIdprofileOwner());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdprofileUser();
		result = 37 * result + this.getIddataSource();
		result = 37 * result + this.getIdprofileOwner();
		return result;
	}

}
