package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShareViewId generated by hbm2java
 */
@Embeddable
public class ShareViewId implements java.io.Serializable {

	@Column(name = "idprofile_owner", nullable = false, insertable = false, updatable = false)
	private int idprofileOwner;

	@Column(name = "iddata_source", nullable = false, insertable = false, updatable = false)
	private int iddataSource;

	public ShareViewId() {
	}

	public ShareViewId(int idprofileOwner, int iddataSource) {
		this.idprofileOwner = idprofileOwner;
		this.iddataSource = iddataSource;
	}

	public int getIdprofileOwner() {
		return this.idprofileOwner;
	}

	public void setIdprofileOwner(int idprofileOwner) {
		this.idprofileOwner = idprofileOwner;
	}

	public int getIddataSource() {
		return this.iddataSource;
	}

	public void setIddataSource(int iddataSource) {
		this.iddataSource = iddataSource;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShareViewId))
			return false;
		ShareViewId castOther = (ShareViewId) other;

		return (this.getIdprofileOwner() == castOther.getIdprofileOwner())
				&& (this.getIddataSource() == castOther.getIddataSource());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdprofileOwner();
		result = 37 * result + this.getIddataSource();
		return result;
	}

}
