package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SharePermissions generated by hbm2java
 */
@Entity
@Table(name = "share_permissions", schema = "public")
public class SharePermissions implements java.io.Serializable {

	@Id
	@Column(name = "idshare_permissions", unique = true, nullable = false)
	private int idsharePermissions;

	@Column(name = "de_permission", nullable = false, length = 45)
	private String dePermission;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sharePermissions")
	private Set<ShareViewWith> shareViewWiths = new HashSet<ShareViewWith>(0);

	public SharePermissions() {
	}

	public SharePermissions(int idsharePermissions, String dePermission) {
		this.idsharePermissions = idsharePermissions;
		this.dePermission = dePermission;
	}

	public SharePermissions(int idsharePermissions, String dePermission,
			Set<ShareViewWith> shareViewWiths) {
		this.idsharePermissions = idsharePermissions;
		this.dePermission = dePermission;
		this.shareViewWiths = shareViewWiths;
	}

	public int getIdsharePermissions() {
		return this.idsharePermissions;
	}

	public void setIdsharePermissions(int idsharePermissions) {
		this.idsharePermissions = idsharePermissions;
	}

	public String getDePermission() {
		return this.dePermission;
	}

	public void setDePermission(String dePermission) {
		this.dePermission = dePermission;
	}

	public Set<ShareViewWith> getShareViewWiths() {
		return this.shareViewWiths;
	}

	public void setShareViewWiths(Set<ShareViewWith> shareViewWiths) {
		this.shareViewWiths = shareViewWiths;
	}

}
