package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * SocialNetwork generated by hbm2java
 */
@Entity
@Table(name = "social_network", schema = "public")
public class SocialNetwork implements java.io.Serializable {

	@Id
	@Column(name = "idsocial_network", unique = true, nullable = false)
	@SequenceGenerator(name = "social_network_seq", sequenceName = "social_network_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="social_network_seq") 
	private int idSocialNetwork;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "social_network_type_idsocial_network_type", nullable = false, insertable = false, updatable = false)
	private SocialNetworkType socialNetworkType;
	
	@Column(name = "social_network_type_idsocial_network_type", nullable = false, insertable = true, updatable = true)
	private Integer idSocialNetworkType;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile_idprofile", nullable = false, insertable = false, updatable = false)
	private Profile profile;
	
	@Column(name = "profile_idprofile", nullable = false, insertable = true, updatable = true)
	private Integer idProfile;

	@Column(name = "user_login", length = 200)
	private String userLogin;

	public SocialNetwork() {
	}

	public SocialNetwork(int idSocialNetwork,
			SocialNetworkType socialNetworkType, Profile profile) {
		this.idSocialNetwork = idSocialNetwork;
		this.socialNetworkType = socialNetworkType;
		this.profile = profile;
		this.idSocialNetworkType = socialNetworkType.getIdSocialNetworkType();
		this.idProfile = profile.getIdprofile();
	}

	public SocialNetwork(int idSocialNetwork,
			SocialNetworkType socialNetworkType, Profile profile, String userLogin) {
		this.idSocialNetwork = idSocialNetwork;
		this.socialNetworkType = socialNetworkType;
		this.profile = profile;
		this.userLogin = userLogin;
		this.idSocialNetworkType = socialNetworkType.getIdSocialNetworkType();
		this.idProfile = profile.getIdprofile();
	}

	public int getIdSocialNetwork() {
		return this.idSocialNetwork;
	}

	public void setIdSocialNetwork(int idSocialNetwork) {
		this.idSocialNetwork = idSocialNetwork;
	}

	public SocialNetworkType getSocialNetworkType() {
		return this.socialNetworkType;
	}

	public void setSocialNetworkType(SocialNetworkType socialNetworkType) {
		this.socialNetworkType = socialNetworkType;
	}
	
	public Integer getIdSocialNetworkType() {
		return idSocialNetworkType;
	}

	public void setIdSocialNetworkType(Integer idSocialNetworkType) {
		this.idSocialNetworkType = idSocialNetworkType;
	}

	public Integer getIdProfile() {
		return idProfile;
	}

	public void setIdProfile(Integer idProfile) {
		this.idProfile = idProfile;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

}
