package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SocialNetworkType generated by hbm2java
 */
@Entity
@Table(name = "social_network_type", schema = "public")
public class SocialNetworkType implements java.io.Serializable {

	@Id
	@SequenceGenerator(name = "social_network_type_seq", sequenceName = "social_network_type_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="social_network_type_seq")
	@Column(name = "idsocial_network_type", unique = true, nullable = false)
	private int idSocialNetworkType;

	@Column(name = "name", length = 200)
	private String name;

	@Column(name = "login_driver", length = 300)
	private String loginDriver;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socialNetworkType")
	private Set<SocialNetwork> socialNetworks = new HashSet<SocialNetwork>(0);

	public SocialNetworkType() {
	}

	public SocialNetworkType(int idSocialNetworkType) {
		this.idSocialNetworkType = idSocialNetworkType;
	}

	public SocialNetworkType(int idSocialNetworkType, String name,
			String loginDriver, Set<SocialNetwork> socialNetworks) {
		this.idSocialNetworkType = idSocialNetworkType;
		this.name = name;
		this.loginDriver = loginDriver;
		this.socialNetworks = socialNetworks;
	}

	public int getIdSocialNetworkType() {
		return this.idSocialNetworkType;
	}

	public void setIdSocialNetworkType(int idSocialNetworkType) {
		this.idSocialNetworkType = idSocialNetworkType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLoginDriver() {
		return this.loginDriver;
	}

	public void setLoginDriver(String loginDriver) {
		this.loginDriver = loginDriver;
	}

	public Set<SocialNetwork> getSocialNetworks() {
		return this.socialNetworks;
	}

	public void setSocialNetworks(Set<SocialNetwork> socialNetworks) {
		this.socialNetworks = socialNetworks;
	}

}
