package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state", schema = "public")
public class State implements java.io.Serializable {

	@Id
	@Column(name = "idstate", unique = true, nullable = false)
	@SequenceGenerator(name = "state_seq", sequenceName = "state_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="state_seq") 
	private int idstate;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_idcountry", nullable = false, insertable = false, updatable = false)
	private Country country;
	
	@Column(name = "country_idcountry", nullable = false, insertable = true, updatable = true)
	private Integer idCountry;

	@Column(name = "nm_state", length = 200)
	private String nmState;

	@Column(name = "statecol", length = 45)
	private String statecol;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	private Set<City> cities = new HashSet<City>(0);

	public State() {
	}

	public State(int idstate, Country country) {
		this.idstate = idstate;
		this.country = country;
		this.idCountry = country.getIdcountry();
	}

	public State(int idstate, Country country, String nmState, String statecol,
			Set<City> cities) {
		this.idstate = idstate;
		this.country = country;
		this.nmState = nmState;
		this.statecol = statecol;
		this.cities = cities;
		this.idCountry = country.getIdcountry();
	}

	public int getIdstate() {
		return this.idstate;
	}

	public void setIdstate(int idstate) {
		this.idstate = idstate;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getNmState() {
		return this.nmState;
	}

	public void setNmState(String nmState) {
		this.nmState = nmState;
	}

	public String getStatecol() {
		return this.statecol;
	}

	public void setStatecol(String statecol) {
		this.statecol = statecol;
	}

	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

	public Integer getIdCountry() {
		return idCountry;
	}

	public void setIdCountry(Integer idCountry) {
		this.idCountry = idCountry;
	}
	
}
