package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TxnLogId generated by hbm2java
 */
@Embeddable
public class TxnLogId implements java.io.Serializable {

	@Column(name = "share_log_idshare_log", nullable = false)
	private int shareLogIdshareLog;

	@Column(name = "field_iddata_field", nullable = false)
	private int fieldIddataField;

	public TxnLogId() {
	}

	public TxnLogId(int shareLogIdshareLog, int fieldIddataField) {
		this.shareLogIdshareLog = shareLogIdshareLog;
		this.fieldIddataField = fieldIddataField;
	}

	public int getShareLogIdshareLog() {
		return this.shareLogIdshareLog;
	}

	public void setShareLogIdshareLog(int shareLogIdshareLog) {
		this.shareLogIdshareLog = shareLogIdshareLog;
	}

	public int getFieldIddataField() {
		return this.fieldIddataField;
	}

	public void setFieldIddataField(int fieldIddataField) {
		this.fieldIddataField = fieldIddataField;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TxnLogId))
			return false;
		TxnLogId castOther = (TxnLogId) other;

		return (this.getShareLogIdshareLog() == castOther
				.getShareLogIdshareLog())
				&& (this.getFieldIddataField() == castOther
						.getFieldIddataField());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getShareLogIdshareLog();
		result = 37 * result + this.getFieldIddataField();
		return result;
	}

}
