package br.com.moretic.vo;

// Generated by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TxnLog generated by hbm2java
 */
@Entity
@Table(name = "txn_log", schema = "public")
public class TxnLog implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "shareLogIdshareLog", column = @Column(name = "share_log_idshare_log", nullable = false)),
			@AttributeOverride(name = "fieldIddataField", column = @Column(name = "field_iddata_field", nullable = false)) })
	private TxnLogId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "field_iddata_field", nullable = false, insertable = false, updatable = false)
	private Field field;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "share_log_idshare_log", nullable = false, insertable = false, updatable = false)
	private ShareLog shareLog;

	@Column(name = "value", length = 1000)
	private String value;

	public TxnLog() {
	}

	public TxnLog(TxnLogId id, Field field, ShareLog shareLog) {
		this.id = id;
		this.field = field;
		this.shareLog = shareLog;
	}

	public TxnLog(TxnLogId id, Field field, ShareLog shareLog, String value) {
		this.id = id;
		this.field = field;
		this.shareLog = shareLog;
		this.value = value;
	}

	public TxnLogId getId() {
		return this.id;
	}

	public void setId(TxnLogId id) {
		this.id = id;
	}

	public Field getField() {
		return this.field;
	}

	public void setField(Field field) {
		this.field = field;
	}

	public ShareLog getShareLog() {
		return this.shareLog;
	}

	public void setShareLog(ShareLog shareLog) {
		this.shareLog = shareLog;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
