define({
	root: ({
	
		// Cabeçalho / Header
		nomeUsuarioGenerico: "Nome do Usu&aacute;rio",
						
		// Main
		rotAbaPerfil: "Perfil",
		rotAbaDados: "Fonte de Dados",
		rotAbaMapa: "Mapa",
		rotAbaAlarmes: "Alarmes",
		rotAbaFaturamento: "Faturamento",
		rotAbaCirculos: "C&iacute;rculos",
		rotDadosPessoais: "Dados Pessoais",
		rotEndereco: "Endere&ccedil;o",
		rotIdioma: "Idioma",
		rotSeguranca: "Seguran&ccedil;a",
		rotHistoricoConta: "Hist&oacute;rico da Conta",
		rotImportar: "Importar",
		rotExportar: "Exportar",
		rotExcluir: "Excluir",
		rotAtualizar: "Atualizar",
		rotCopiar: "Copiar",
		rotTransformar: "Transformar",
		rotCompartilhar: "Compartilhar",
		rotDrivers: "Drivers",
		rotTarefa: "Tarefa",
		rotHistorico: "Hist&oacute;rico",
		rotFerramentas: "Ferramentas",
		rotSalvar: "Salvar",
		rotFiltrar: "Filtrar",
		rotConfigurar: "Configurar",
		rotImagem: "Imagem",
		rotNovo: "Novo",
		rotTransacoes: "Transa&ccedil;&otilde;es",
		rotCreditoDebito: "Cr&eacute;dito & D&eacute;bito",
		rotContatos: "Contatos",
		rotCirculos: "C&iacute;rculos",
		
		// Telas de Splash
		descDadosPessoais: "Preencha seu dados pessoais que voc&ecirc; deseja que outros usu&aacute;rios visualizem",
		descEndereco: "Informe seu endere&ccedil;o",
		descIdioma: "Selecione o idioma de sua prefer&ecirc;ncia",
		descSeguranca: "Configure informa&ccedil;&otilde;es importantes de seguran&ccedil;a",
		descHistoricoConta: "Visualize todas as atividades realizadas em sua conta",
		descImportarDados: "Realize importa&ccedil;&atilde;o de dados &agrave; partir de diversas fontes e formatos",
		descExportarDados: "Exporte os dados desejados em muitos formatos",
		descCopiarDados: "Copiar dados para outra fonte",
		descTransformarDados: "Cruze dados e gere de uma nova fonte de informa&ccedil;&atilde;o",
		descCompartilharDados: "Compartilhe seus dados com outros usu&aacute;rios",
		descDriversDados: "Crie seu pr&oacute;prio procedimento de capta&ccedil;&atilde;o de dados",
		descTarefasDados: "Agende tarefas para manusear dados",
		descHistoricoDados: "Veja o hist&oacute;rico de altera&ccedil;&atilde;o de suas fontes de dados",
		descVisualizarMapa: "Visualizar fontes de dados e servi&ccedil;os compartilhados no mapa",
		descFiltrarMapa: "Filtrar servi&ccedil;os e informa&ccedil;&otilde;es a seu crit&eacute;rio",
		descCamadasMapa: "Configure suas camadas de dados",
		descExportarMapa: "Exporte seus dados como servi&ccedil;os e compartilhe no mapa",
		descAtualizarAlarme: "Atualize os alarmes",
		descFiltrarAlarme: "Localize os alarmes com ajuda de filtros",
		descConfigurarAlarme: "Configura&ccedil;&atilde;o geral dos alarmes",
		descCreditoFaturamento: "Gerencie seus ganhos",
		descDebitoFaturamento: "Gerencie suas faturas",
		descTransacoesFaturamento: "Hist&oacute;rico financeiro",
		rotImportarContatos: "Importar Contatos",
		descImportarContatosCirculos: "Importe seus contatos de redes sociais ou arquivos",
		rotNovoContato: "Novo Contato",
		descNovoContatoCirculos: "Cadastre um novo contato",
		descCirculos: "Gerencie seus c&iacute;rculos de contatos",
				
		// Módulo Perfil		
		btSalvarPerfil: "Salvar",
		tituloDadosPessoais: "Dados pessoais",
		rotNomePerfil: "Nome",
		rotEmailPerfil: "Email",
		rotDataNascPerfil: "Data de Nasc.",
		cpfCnpjPassaporte: "CPF/CNPJ/Passaporte",
		rotSenhaPerfil: "Senha",
		rotConfirmaSenhaPerfil: "Confirme a senha",
		rotBioPerfil: "Bio",
		btAceitoTermosPerfil: "Aceito os termos de uso",
		rotTelefonePerfil: "Telefone",
		rotCodigoAreaPerfil: "Cod. &Aacute;rea",
		rotAvatarPerfil: "Avatar",
		tituloEnderecoPerfil: "Endere&ccedil;o",
		rotRuaPerfil: "Rua",
		rotComplementoPerfil: "Complemento",
		rotCepPerfil: "CEP",
		rotBairroPerfil: "Bairro",
		rotPaisPerfil: "Pa&iacute;s",
		rotEstadoPerfil: "Estado",
		rotCidadePerfil: "Cidade",
		selecionePais: "Selecione o Pa&iacutes",
		selecioneEstado: "Selecione o Estado",
		selecioneCidade: "Selecione a Cidade",
		seuEndereco: "Seu Endereço",
		tituloIdiomaPerfil: "Idiomas",
		rotIdiomaPerfil: "Idioma",
		rotVarianteIdiomaPerfil: "Variante do Idioma",
		rotOutrosPerfil: "Outros",
		tituloSegurancaPerfil: "Seguran&ccedil;a da Conta",
		rotEmailRecuperaPerfil: "Email para recuperar senha",
		rotCelularPerfil: "Celular",
		rotFraseSecretaPerfil: "Frase Secreta",
		tituloHistoricoPerfil: "Log de Acesso da Conta",
		rotDe: "De",
		rotAte: "at&eacute;",
		btBuscar: "Buscar",
		rotID: "ID",
		rotData: "Data",
		rotTipo: "Tipo",
		rotIP: "IP",
		verifiqueSenha: "A senha não coincide",
		
		// Módulo Dados
		tituloImportarDados: "Importa&ccedil;&atilde;o de Dados",
		p1ImportacaoDados: "Selecione uma fonte de dados ao lado e escolha o formato de importa&ccedil;&atilde;o (passo 1 de n)",
		tituloExportarDados: "Exporta&ccedil;&atilde;o de Dados",
		p1ExportacaoDados: "Selecione uma fonte de dados ao lado e escolha o formato de exporta&ccedil;&atilde;o (passo 1 de n)",
		tituloCopiarDados: "Copiar Fonte de Dados",
		p1CopiarDados: "Selecione uma fonte de dados &agrave; esquerda para efetuar a c&oacute;pia!",
		rotNomeDestinoDados: "Nome da Fonte Destino",
		rotCopiarDados: "Copiar dados",
		rotCopiarCompartDados: "Copiar compartilhametos",		
		tituloTransformarDados: "Transforma&ccedil;&atilde;o de Dados",
		p1TransformarDados: "Selecione uma ou mais fontes de dados &agrave; esquerda e construa sua transforma&ccedil;&atilde;o de dados",
		rotGZIPDados: "Trafegar em GZIP",
		rotHttpsDados: "Trafegar em https",		
		rotNomeCampoDados: "Nome do Campo",
		rotNomeTransformacaoDados: "Nome da transforma&ccedil;&atilde;o",
		btExcluir: "Excluir",
		btVincularCamposDados: "Vincular campos",
		btAgruparCamposDados: "Agrupar campos",
		btFiltrarDados: "Filtrar",
		btLayoutDados: "Layout",
		btTestarDados: "Testar",
		tituloCompartilharDados: "Compartilhar",
		p1CompartilharDados: "Selecione as fontes de dados &agrave; esquerda para compartilhar como servi&ccedil;os para seus c&iacute;rculos.",
		rotEnviarParaDados: "Enviar para",
		rotPermissaoDados: "Permiss&atilde;o",
		rotVisibilidadeDados: "Visibilidade",
		p1DriversDados: "Drivers publicados no framework. Utilize a ferramenta abaixo para instalar o seu driver!",
		rotIconeDriverDados: "&Iacute;cone",
		btTestarDriverDados: "Testar driver",
		rotDescricaoDriver: "Descri&ccedil;&atilde;o",
		tituloTarefasDados: "Tarefas",
		p1TarefasDados: "Selecione uma fonte de dados &agrave; esquerda e configure sua tarefa para sincroniz&aacute;-la.",
		rotNomeTarefaDados: "Nome da tarefa",
		rotDataTarefaDados: "Data",
		rotHoraTarefaDados: "Hora",
		rotDiariamenteDados: "Executar diariamente",
		rotSincronTarefaDados: "Sincronizar a cada<br>requisi&ccedil;&atilde;o",
		obsSincronTarefaDados: "Maior custo de processamento",
		rotIntervaloTarefaDados: "Intervalo de Sincroniza&ccedil;&atilde;o",
		periodoExecucaoTarefa: "Per&iacute;odo de execu&ccedil;&atilde;o",
		btNovaTarefaDados: "Nova",
		tituloHistoricoDados: "Hist&oacute;rico de transa&ccedil;&otilde;es",
		p1HistoricoDados: "Utilize o filtro abaixo para visualizar as transações de dados realizadas.",
		fonteDados: "Fonte de Dados",
		fontesDados: "Fontes de Dados",
		importacoesPendentes: "Importa&ccedil;&otilde;es Pendentes",
		
		tituloImportBancoDados: "Importar Banco de Dados (Passo 1 de 2)",
		nomeFonteDados: "Nome da fonte de dados",
		nomeBaseDados: "Nome da base de dados",
		tipoBaseDados: "Tipo da base de dados",
		testarConexao: "Testar Conex&atilde;o",
		tituloImportKml: "Importar Kml",		
		p1ImportADConnection: "Preencha os campos e teste a conex&atilde;o (Passo 1 de 2)",
		p1ImportFtpSelection: "Selecione o diret&oacute;rio, marque os tipos de arquivos e confira a lista dos arquivos para importa&ccedil;&atilde;o (Passo 2 de 2)",
		tituloImportDBSelection: "Importar Banco de Dados",
		p1ImportDBSelection: "Arraste as tabelas (Passo 2 de 2)",
		localArquivo: "Url do Arquivo",
		p1ImportCsv: "Selecione os campos desejados e utilize as setas para inser&iacute;-los na fonte de dados (Passo 2 de 2)",
		p1ImportFtpConection: "Preencha os dados e teste a conexão (Passo 1 de 2)",
		p1ImportJson: "Selecione os campos desejados e utilize as setas para inser&iacute;-los na fonte de dados (Passo 2 de 2)",
		importarLdap: "Importar LDAP (Passo 1 de 2)",
		pesquisaLdap: "Pesquisa LDAP",
		tituloImportImportWsdl: "Importar dados de Web Services",
		p1ImportWsdl: "Selecione o serviço de dados e digite um filtro para buscar (Passo 2 de 2)",
		filtroWsdl: "Filtro",
		dataModificacao: "Data Modifica&ccedil;&atilde;o",
		enviarDestePC: "Enviar deste computador",
		abrirDiretorioPendencias: "Abrir diret&oacute;rio de pend&ecirc;ncias",
		enderecoNaoEncontrado: "Nenhum endereço encontrado",
		enderecoAbrangente: "O resultado &eacute; muito abrangente. Informe a rua e o n&uacute;mero",
		
		// Módulo Mapa
		tituloMapConfig: "Configura&ccedil;&atilde;o do mapa",
		
		// Módulo Alarmes
		
		// Módulo Faturamento
		tituloHistoricoTransacoes: "Hist&oacute;rico de transa&ccedil;&otilde;es finaceiras",
		tituloCreditoDebito: "Cr&eacute;dito / D&eacute;bito",
		p1CreditoDebito: "Configure suas formas de pagamento e recebimento.",
		paypal: "Paypal",
		p1Paypal: "Informe seu e-mail de cadastro no PayPal para recebimento.",
		pagSeguro: "PagSeguro",
		p1Pagseguro: "Informe seu e-mail de cadastro no PagSeguro para recebimento.",
		p1FormBanco: "Informe seus dados para recebimento via banco.",
		btNovaConta: "Nova",
		selecioneCartao: "Selecione um cart&atilde;o",
		numeroCartao: "N&uacute;mero do cart&atilde;o",
		dataExpiracao: "Data de expira&ccedil;&atilde;o",
		cvc: "CVC",
		
		// Módulo Círculos
		tituloContatosCirculos: "Contatos",
		rotDigiteNome: "digite um nome aqui",
		btNovoContato: "Novo",
		btCirculo: "C&iacute;rculo",
		tituloCirculos: "C&iacute;rculos",
		
		// Genéricos
		gNome: "Nome",
		gString: "String",
		gNumerico: "Num&eacute;rico",
		gBlob: "Blob",
		gLogico: "L&oacute;gico",
		gMascara: "M&aacute;scara",
		gID: "ID",
		gInfo: "Informa&ccedil;&atilde;o",
		gVisualizar: "Visualizar",
		gEditar: "Editar",
		gPublico: "P&uacute;blico",
		gPrivado: "Privado",
		gDriver: "Driver",
		gDrivers: "Drivers",
		gIcone: "&Iacute;cone",
		gDescricao: "Descri&ccedil;&atilde;o",
		gClasspath: "Classpath",
		gHora: "Hora",
		gData: "Data",
		gUsuario: "Usu&aacute;rio",
		gOperacao: "Opera&ccedil;&atilde;o",
		gRegiao: "Regi&atilde;o",
		gConfiguracao: "Configura&ccedil;&atilde;o",
		gTipo: "Tipo",
		gCodigo: "C&oacute;digo",
		gMediador: "Mediador",
		gConta: "Conta",
		gAgencia: "Ag&ecirc;ncia",
		gBanco: "Banco",
		gCirculo: "C&iacute;rculo",
		gMembros: "Membros",
		gEmail: "E-mail",
		gUrl: "Url",
		gPorta: "Porta",
		gSenha: "Senha",
		gLink: "Link",
		gCartao: "Cart&atilde;o",
		gContaBancaria: "Conta Banc&aacute;ria",
		gBandeira: "Bandeira",
		gAnterior: "Anterior",
		gProximo: "Pr&oacute;ximo",
		gTestar: "Testar",
		gFinalizar: "Finalizar",
		gCredito: "Cr&eacute;dito",
		gDebito: "D&eacute;bito",
		gCamadas: "Camadas",
		gTamanho: "Tamanho"
	
	}),
	"en": true,
	"pt-pt": true

});