define({

	// Cabeçalho / Header
	nomeUsuarioGenerico: "User's Name",
	
	// Main
	rotAbaPerfil: "Profile",
	rotAbaDados: "Data Source",
	rotAbaMapa: "Map",
	rotAbaAlarmes: "Alarms",
	rotAbaFaturamento: "Billing",
	rotAbaCirculos: "Circles",
	rotAbaLoja: "Store",
	rotDadosPessoais: "Personal Info",
	rotEndereco: "Address",
	rotIdioma: "Language",
	rotSeguranca: "Security",
	rotHistoricoConta: "Account History",
	rotImportar: "Import",
	rotExportar: "Export",
	rotExcluir: "Exclude",
	rotAtualizar: "Refresh",
	rotCopiar: "Copy",
	rotTransformar: "Transform",
	rotVisualizarDados: "View Data",
	rotCompartilhar: "Share",
	rotDrivers: "Drivers",
	rotTarefa: "Task",
	rotHistorico: "History",
	rotFerramentas: "Tools",
	rotSalvar: "Save",
	rotFiltrar: "Search",
	rotConfigurar: "Configure",
	rotImagem: "Image",
	rotNovo: "New",
	rotTransacoes: "Transactions",
	rotCreditoDebito: "Credit & Debit",
	rotContatos: "Contacts",
	rotCirculos: "Circles",
	
	// Telas de Splash
	descDadosPessoais: "Fill your personal info that you want others to see",
	descEndereco: "Inform your address",
	descIdioma: "Pick the language of your preference",
	descSeguranca: "Configure important security info",
	descHistoricoConta: "Visualize all activity did in your account",
	descImportarDados: "Perform importation of data from different sources and formats",
	descExportarDados: "Export the desired data into many formats",
	descCopiarDados: "Copy data to another source",
	descTransformarDados: "Cross data and generate a new information source",
	descCompartilharDados: "Share your data with other users",
	descDriversDados: "Create your own procedure to collect data",
	descTarefasDados: "Schedule tasks to handle data",
	descHistoricoDados: "View the changes history for your data sources",
	descVisualizarMapa: "View data sources and services shared on the map",
	descFiltrarMapa: "Search services and information you want",
	descCamadasMapa: "Configure your layers of data",
	descExportarMapa: "Export your data as a service and share on the map",
	descAtualizarAlarme: "Refresh the alarms",
	descFiltrarAlarme: "Search alarms",
	descConfigurarAlarme: "General configuration for alarms",
	descCreditoFaturamento: "Manage your earnings",
	descDebitoFaturamento: "Manage your bills",
	descTransacoesFaturamento: "Financial history",
	rotImportarContatos: "Import Contacts",
	descImportarContatosCirculos: "Import your contacts from social networks or files",
	rotNovoContato: "New Contact",
	descNovoContatoCirculos: "Register a new contact",
	descCirculos: "Manage your circles of contacts",
	
	// Módulo Perfil	
	btSalvarPerfil: "Save",
	tituloDadosPessoais: "Personal Data",
	rotNomePerfil: "Name",
	rotEmailPerfil: "Email",
	rotDataNascPerfil: "Birth date",
	cpfCnpjPassaporte: "CPF/CNPJ/Passport",
	rotSenhaPerfil: "Password",
	rotConfirmaSenhaPerfil: "Confirm the password",
	rotBioPerfil: "Bio",
	btAceitoTermosPerfil: "I accept the terms of use",
	rotTelefonePerfil: "Telephone",
	rotCodigoAreaPerfil: "Area Code",
	rotAvatarPerfil: "Avatar",
	tituloEnderecoPerfil: "Address",
	rotRuaPerfil: "Street",
	rotComplementoPerfil: "Complement",
	rotCepPerfil: "ZIP code",
	rotBairroPerfil: "District",
	rotPaisPerfil: "Country",
	rotEstadoPerfil: "State",
	rotCidadePerfil: "City",
	selecionePais: "Select the Country",
	selecioneEstado: "Select the State",
	selecioneCidade: "Select the City",
	seuEndereco: "Your Address",
	tituloIdiomaPerfil: "Languages",
	rotIdiomaPerfil: "Language",
	rotVarianteIdiomaPerfil: "Language variant",
	rotOutrosPerfil: "Others",
	tituloSegurancaPerfil: "Account Security",
	rotEmailRecuperaPerfil: "Password recovery e-mail",
	rotCelularPerfil: "Celphone",
	rotFraseSecretaPerfil: "Passphrase",
	tituloHistoricoPerfil: "Account Access Log",
	rotDe: "From",
	rotAte: "to",
	btBuscar: "Search",
	rotID: "ID",
	rotData: "Date",
	rotTipo: "Type",
	rotIP: "IP",
	verifiqueSenha: "The password does not match",
	eula: "End User License Agreement",
	aceiteEula: "You must accept the End User License Agreement to continue.",
	informeEndereco: "You must inform your address.",
	
	// Módulo Dados	
	tituloImportarDados: "Data Import",
	p1ImportacaoDados: "Select a data source aside and pick the format to be imported to (step 1 of n)",
	tituloExportarDados: "Data Export",
	p1ExportacaoDados: "Select a data source aside and pick the format to be exported from (step 1 of n)",
	tituloCopiarDados: "Copy Data Source",
	p1CopiarDados: "Select a data source on the left to make the copy!",
	rotNomeDestinoDados: "Destiny source name",
	rotCopiarDados: "Copy data",
	rotCopiarCompartDados: "Copy shares",
	tituloTransformarDados: "Data Transform",
	p1TransformarDados: "Select one or more data sources on the left and make your data transform",
	rotGZIPDados: "Transfer in GZIP",
	rotHttpsDados: "Traffic in https",
	rotNomeCampoDados: "Field name",
	rotNomeTransformacaoDados: "Transformation name",
	btExcluir: "Exclude",
	btVincularCamposDados: "Link fields",
	btAgruparCamposDados: "Group fields",
	btFiltrarDados: "Search",
	btLayoutDados: "Layout",
	btTestarDados: "Test",
	tituloCompartilharDados: "Share",
	p1CompartilharDados: "Select the data sources on the left to share as service to your circles.",
	rotEnviarParaDados: "Send to",
	rotPermissaoDados: "Permission",
	rotVisibilidadeDados: "Visibility",
	p1DriversDados: "Drivers published on the framework. Use the tool below to install your driver!",
	rotIconeDriverDados: "Icon",
	btTestarDriverDados: "Test driver",
	rotDescricaoDriver: "Description",
	tituloTarefasDados: "Tasks",
	p1TarefasDados: "Select a data source on the left and configure your task to synchronize it.",
	rotNomeTarefaDados: "Task Name",
	rotDataTarefaDados: "Date",
	rotHoraTarefaDados: "Hour",
	rotDiariamenteDados: "Daily run",
	rotSincronTarefaDados: "Synchronize to each request",
	obsSincronTarefaDados: "Higher process cost",
	rotIntervaloTarefaDados: "Synchronization interval",
	periodoExecucaoTarefa: "Execution period",
	btNovaTarefaDados: "New",
	tituloHistoricoDados: "Transactions History",
	p1HistoricoDados: "Use the filter below to view the data transactions made.",
	fonteDados: "Data Source",
	fontesDados: "Data Sources",
	importacoesPendentes: "Pending Imports",
	
	tituloImportBancoDados: "Import Database (Step 1 of 2)",
	nomeFonteDados: "Data source's name",
	nomeBaseDados: "Database name",
	tipoBaseDados: "Database type",
	testarConexao: "Test Connection",
	tituloImportKml: "Import KML",	
	p1ImportADConnection: "Fill the fields and test the connection (step 1 of 2)",
	p1ImportFtpSelection: "Select the directory, pick the file types and check the listed files to import (Step 2 of 2)",
	tituloImportDBSelection: "Import Database",
	p1ImportDBSelection: "Drag the tables (Step 2 of 2)",
	localArquivo: "File Url",
	p1ImportCsv: "Select the desired fields and use the arrows to insert them into the data source (Step 2 of 2)",
	p1ImportFtpConection: "Fill the fields and test the connection (Step 1 of 2)",
	p1ImportJson: "Select the desired fields and use the arrows to insert them into the data source (Step 2 of 2)",
	importarLdap: "Import LDAP (Step 1 of 2)",
	pesquisaLdap: "LDAP query",
	tituloImportImportWsdl: "Import data from Web Services",
	p1ImportWsdl: "Select the data service and type a query to search (Step 2 of 2)",
	filtroWsdl: "Query",
	dataModificacao: "Date Modified",
	enviarDestePC: "Upload from this computer",
	abrirDiretorioPendencias: "Open directory of pendencies",
	enderecoNaoEncontrado: "No addresses was found",
	enderecoAbrangente: "The result is too wide. Inform the street and number",
	tituloUpload: "File Upload",
	
	// Módulo Mapa
	tituloMapConfig: "Map configuration",
	
	// Módulo Alarmes	
	
	// Módulo Faturamento	
	tituloHistoricoTransacoes: "History of Financial Transactions",
	tituloCreditoDebito: "Credit / Debit",
	p1CreditoDebito: "Configure your forms of payment and receiving.",
	paypal: "Paypal",
	p1Paypal: "Inform your PayPal e-mail for receiving.",
	pagSeguro: "PagSeguro",
	p1Pagseguro: "Inform your PagSeguro e-mail for receiving.",
	p1FormBanco: "Inform your data for receiving via bank.",
	btNovaConta: "New",
	selecioneCartao: "Select a card",
	numeroCartao: "Card number",
	dataExpiracao: "Expiration date",
	cvc: "CVC",
	
	// Módulo Círculos
	
	tituloContatosCirculos: "Contacts",
	rotDigiteNome: "type a name here",
	btNovoContato: "New",
	btCirculo: "Circle",
	tituloCirculos: "Circles",
	
	// Genéricos
	gNome: "Name",
	gString: "String",
	gNumerico: "Numeric",
	gBlob: "Blob",
	gLogico: "Logic",
	gMascara: "Mask",
	gID: "ID",
	gInfo: "Information",
	gVisualizar: "View",
	gEditar: "Edit",
	gPublico: "Public",
	gPrivado: "Private",
	gDriver: "Driver",
	gDrivers: "Drivers",
	gIcone: "Icon",
	gDescricao: "Description",
	gClasspath: "Classpath",
	gHora: "Time",
	gData: "Date",
	gUsuario: "User",
	gOperacao: "Operation",
	gRegiao: "Region",
	gConfiguracao: "Configuration",
	gTipo: "Type",
	gCodigo: "Code",
	gMediador: "Mediator",
	gConta: "Account",
	gAgencia: "Agency",
	gBanco: "Bank",
	gCirculo: "Circle",
	gMembros: "Members",
	gEmail: "E-mail",
	gUrl: "Url",
	gPorta: "Port",
	gSenha: "Password",
	gLink: "Link",
	gCartao: "Card",
	gContaBancaria: "Bank Account",
	gBandeira: "Flag",
	gAnterior: "Previous",
	gProximo: "Next",
	gTestar: "Test",
	gFinalizar: "Finish",
	gCredito: "Credit",
	gDebito: "Debit",
	gCamadas: "Layers",
	gTamanho: "Size",
	gVerifiqueDados: "Verify your data once again.",
	gAtencao: "Attention",
	gNaoSalvou: "It was not possible to save the data.",
	gCausa: "Cause",
	gErro: "Error",
	gSalvoSucesso: "Data saved successfully."
});